README.md, config/datocms/migrations/1705751291_redirectRules.ts, datocms-environment.ts, docs/decision-log/2024-01-20-editable-redirects.md, docs/routing.md, package.json, scripts/download-redirects.ts, src/blocks/InternalLink/README.md
- Adds editable redirects to the CMS (Redirect Rule model).
- Adds postbuild script to download redirects and save to a `_redirects` file.
- Adds documentation on routing, including redirects.
Resolves #64
1. Review the new Redirect Rules model in the CMS
2. Create or edit Redirect Rules in the CMS (requires rebuild to take effect)
3. Open the preview deployment
4. Verify that the redirect rules work (also try reordering them):
- [`/redirect-placeholder/:slug/`](https://ca6875c4.head-start.pages.dev/redirect-placeholder/overview-page/) -> [`/en/overview-page/`](https://ca6875c4.head-start.pages.dev/en/overview-page/)
- [`/redirect-wildcard/*`](https://ca6875c4.head-start.pages.dev/redirect-wildcard/overview-page/demos/tables/) -> …
=> feature: Editable redirects

datocms-environment.ts, docs/decision-log/2023-10-24-datocms-env-file.md
- Adds decision log entry on why we use a static configuration file for why DatoCMS environment.
- Links to the decision from the configuration file so people can find the motivation.
Resolves #106 
Review new decision log entry
=> docs: decision to use DatoCMS environment configuration file

config/datocms/migrations/1706472108_videoBlock.ts, datocms-environment.ts, package-lock.json, package.json, src/blocks/Blocks.astro, src/blocks/Blocks.d.ts, src/blocks/EmbedBlock/embeds/Default.client.ts, src/blocks/TextBlock/TextBlock.fragment.graphql, src/blocks/VideoBlock/README.md, src/blocks/VideoBlock/VideoBlock.astro, src/blocks/VideoBlock/VideoBlock.client.ts, src/blocks/VideoBlock/VideoBlock.fragment.graphql, src/blocks/VideoBlock/VideoFallback.astro, src/blocks/VideoBlock/VideoTextTracks.astro, src/blocks/VideoEmbedBlock/README.md, src/components/LocaleSelector/LocaleSelector.astro, src/lib/i18n.ts, src/pages/[locale]/[...path]/index.query.graphql, src/pages/[locale]/index.query.graphql
Adds Video Block that renders a video uploaded in DatoCMS with a cover image, caption, support for subtitles and options to autoplay, mute and loop. Features (also in block readme):
- Privacy first alternative to [Video Embed Block](../VideoEmbedBlock/), as video uploaded in DatoCMS is served without tracking (no consent required).
- Supports video streaming with adaptive bitrate (using HLS) for best UX and performance.
- Fallback to mp4 video when streaming is not available.
- Fallback to video download link when HTML video element is not supported.
- Supports subtitle tracks for enhanced accessibility, automatically selecting default locale when available.
- Supports figcaption defaulting to external video's title and optional custom title override.
- Supports autoplay, mute and loop.
- …
=> feature: Video Block

config/datocms/migrations/1706526286_pageModelNames.ts, datocms-environment.ts, docs/cms-content-modelling.md, src/blocks/InternalLink/InternalLink.astro, src/blocks/InternalLink/InternalLink.fragment.graphql, src/pages/[locale]/404.astro, src/pages/[locale]/404.query.graphql, src/pages/[locale]/index.astro, src/pages/[locale]/index.query.graphql
- Adds Page postfix to `HomePage` and `notFoundPage` to match docs on content modelling.
- Adds missing bodyBlocks to notFoundPage (should have been there already).
- Changes field name recommendation from `theme` to `style` to fit more use cases like `primary` on actions/buttons/links)
N/A
1. Open deploy preview
2. Verify everything still works as before, including 404 page.
- ~~I have notified a reviewer~~ (small changes to match documentation)
=> chore: Page postfix on models; blocks on Not Found Page

config/preview.ts, docs/preview-mode.md, src/components/PreviewMode/PreviewMode.astro, src/components/PreviewMode/PreviewModeLogin.astro, src/pages/[locale]/[...path]/_Page.astro, src/pages/[locale]/[...path]/index.astro
Errors occurred in preview mode caused by incorrect API route URLs and the new nested pages route (`[...path]`).
This PR resolves those by:
- Adds trailing slashes to preview API routes in templates and docs, as they are now required.
- Handle page route mismatch, caused by [open Astro issue](https://github.com/withastro/astro/issues/9103).
N/A
2. Enter preview secret
3. Verify you enter preview mode
4. Verify home page(s) render
5. Verify generic page(s) render
6. Exit preview mode
7. Verify that works too
- ~~I have notified a reviewer~~
=> fix: Preview mode routing

src/components/SeoHead.astro
Adds `og:url` to SeoHead, using the `canonical` URL value.
N/A
2. View source code (or use Heads Up to inspect)
3. Verify `og:url` is set correctly
- ~~I have notified a reviewer~~ (tiny improvement)
=> feature: og:url in SeoHead

.vscode/settings.json
- Removes vscode settings.json
Resolves #133 
1. Grab an Astro file like the table block for example.
2. Change the single quotes from an import to double quotes.
3. Change de double quote from an html attribute to single quotes.
4. Do right mouse click and select `Format Document`.
5. Document should be formatted back to the previous state.
=>  133 VSCode settings replaces double quotes with single quotes in html

src/components/SkipLink/SkipLink.astro
Adds `datocms-no-index` attribute to the SkipLink component so it no longer appears in the search results.
N/A. Screenshot of issue:
2. View source code
3. Verify SkipLink has a `datocms-no-attribute` just like the header and footer.
=> fix(SkipLink): add datocms-no-index

src/lib/i18n.ts
- Adds console warning to the translation function when there is no translation for that key
Resolves #129 
1. Open project on localhost
2. Add a random translation somewhere in the home page
3. There should be a yellow console warning in your terminal (Not in the browser console)
=> 129-log-warning-for-missing-translation

src/blocks/TextImageBlock/TextImageBlock.astro
Fixes classname for layout with `flex-direction: row;` as both layout classes were showing the text and image in the same layout instead of opposites.
N/A
2. Navigate to [text image block demo](https://fix-text-image-block-layout.head-start.pages.dev/en/demos/text-image-block/)
3. Verify that different layouts show text and image in different order
=> fix: TextImageBlock layout classname for direction row

src/components/Breadcrumbs/Breadcrumbs.astro
First breadcrumb linking to home page was missing the locale, causing unneeded redirects. This PR adds it.
N/A
2. Navigate to any nested page
3. Tap on home breadcrumb
4. Verify that it directly navigates to the home page in the right locale without redirects
=> fix(breadcrumbs): locale in home url

src/layouts/Default.astro
Home link in site header was missing the locale, causing unneeded redirects. This PR adds it.
N/A
2. Tap on home link in header
3. Verify that it directly navigates to the home page in the right locale without redirects
=> fix(Layout): locale in home link

src/blocks/ImageBlock/Image.astro
- Set a max-width of 100% in order to not render images larger then their intrinsic size
- Add an imgix parameter of fit: max in order to not upscale images larger then their intrinsic size
Resolves #151
1. Open preview link and see homepage. The voorhoede logo is an a png coming from imgix. The cake is an svg with a width an height set to 100px.
=> fix(Image): make sure images do not render larger than their intrinsic size

src/lib/datocms.ts
- Add error handling for both graphql errors as fetch errors when requesting datocms
Resolves #149
1. Locally screw up a graphql file and see relevant errors
2. Locally screw up datocmsRequest in datocms.ts, e.g. not passing headers and see a relevant error instead of page data being undefined
=> Data fetching error from dato not shown in development

src/blocks/VideoEmbedBlock/VideoEmbedBlock.astro
Correct layer order (z-index) of elements in Video Embed Block.
N/A
I experienced this issue while developing the No Dodos website a while back. I kept this fix as a note, but forgot how to reproduce the issue 🤷 .
=> fix(VideoEmbedBlock): correct layer order (z-index)

package-lock.json, package.json, src/assets/icons/play.svg, src/blocks/VideoEmbedBlock/PlayButton.astro, src/blocks/VideoEmbedBlock/VideoEmbedBlock.astro, src/blocks/VideoEmbedBlock/VideoEmbedBlock.client.ts
- Adds consent alert to VideoEmbedBlock
Resolves #137 
2. Scroll down to the Video
3. Click on the video
4. There should be an overlay popping up asking for permission
5. Click the allow button.
6. Video should start.
7. Check if this permission is added in the local storage.
=> 137-consent-prompt-for-video-embed-block

.eslintrc.cjs, .gitignore, astro.config.ts, config/preview.ts, package-lock.json, package.json, src/blocks/EmbedBlock/embeds/Default.astro, src/components/Breadcrumbs/Breadcrumbs.astro, src/components/PreviewMode/PreviewModeSubscription.astro, src/components/Tabs/Tabs.client.ts, src/env.d.ts, src/lib/datocms.ts, src/middleware.ts, src/pages/api/demo/geo.ts, src/pages/api/preview/enter.ts, tsconfig.json
- Upgrade astro, astrojs/cloudflare and astrojs/check
- Changes related to [https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md#1000](https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md#1000) and [https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md#processenv](https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md#processenv)
- Fixed some linting configuration and linting errors/warnings
Resolves #150 
1. Open [https://preview-throws-500-due-to-as.head-start.pages.dev/en/](https://preview-throws-500-due-to-as.head-start.pages.dev/en/)
2. The homepage should be previewable by entering the secret, where [https://preview.head-start.pages.dev/en/](https://preview.head-start.pages.de …
=> Upgrade astro and cloudflare adapter to latest version

package-lock.json, package.json, tsconfig.json
- Adds TS plugin for .astro files, so it won't be highlighted as an error.
Resolves #175
=> Fix: Astro imports in typescript

src/blocks/ImageBlock/Image.astro, src/blocks/ImageBlock/Image.client.ts, src/env.d.ts
- Adds a custom element with logic to remove the background image if image loads
Resolves #132 
2. Check in the inspector if images which are wrapped in an `enhanced-image` tag if they have a background image in the styles.
3. You can also go to your network tab and enable throttling to better see it happening (But with throttling the styles do not always seem to match with the real DOM, so you have te click the element away or try to disable the background image and you'll see it change and or cannot disable the rule).
- ~I have made updated relevant documentation files (in project README, docs/, etc)~
=> feature: Remove background image when image is loaded

config/preview.ts, src/lib/datocms.ts, src/middleware.ts
It appears getSecret is broken when used on env variables that are not defined in the .env file. Thus breaking previews in our case. I replaced all getSecret references and directly imported the variables from astro:env/server, which is also possible according to https://docs.astro.build/en/reference/configuration-reference/#experimentalenv. Note that what they write there about getSecret didnt work!
Both urls below should either show you a login screen or should show you the "In preview mode banner":
So main doesnt work, see https://preview.head-start.pages.dev/en/
The PR preview does work: https://fix-previews-not-working.head-start.pages.dev/en/
=> fix(env): do not use getSecret but import env variables directly since getSecret is broken

src/blocks/ImageBlock/Image.astro, src/blocks/ImageBlock/ImageBlock.fragment.graphql, src/blocks/ImageBlock/ImageBlock.test.ts
- Fixes layout shifts by setting width and height on images
Issue seen and fixed in Happy Labs.
1. Open preview link in English
2. Open inspector
3. Go to network tab
4. Enable `ignore cache` and set network throttling on
5. You'll see the image size being reserved.
- ~I have made updated relevant documentation files (in project README, docs/, etc)~
=> Fix: Layout shifts caused by images

CHANGELOG.md, README.md, docs/upgrading.md
Adds documentation on how to upgrade to a newer version of Head Start by applying changes made to your own project.
Resolves #86
1. Go to an existing project based on Head Start
2. Follow the upgrade guide
3. Verify the changes are applied
=> docs: Upgrading

astro.config.ts, config/datocms/migrations/1730927867_fileModel.ts, datocms-environment.ts, package-lock.json, package.json, src/assets/icons/download.svg, src/blocks/TextBlock/TextBlock.fragment.graphql, src/blocks/TextImageBlock/TextImageBlock.fragment.graphql, src/components/LinkToFile/LinkToFile.astro, src/components/LinkToFile/LinkToFile.test.ts, src/components/LinkToFile/README.md, src/components/LinkToRecord/LinkToRecord.astro, src/lib/datocms/index.ts, src/lib/routing/FileRoute.fragment.graphql, src/lib/routing/index.test.ts, src/lib/routing/index.ts, src/lib/routing/redirects.test.ts, src/pages/[locale]/[...path]/index.astro, src/pages/files/[...filename].ts
- Adds a new `file` model that provides a generic pattern for content editors to add and reference files.
- Editors can upload an asset and link to the file records in text and other fields.
- Editors can select the locale of a file for improved accessibility.
- Adds a `LinkToFile` component. See its README for details.
- Adds a `/files/[...filename].ts` route to proxy files, so they can be used as downloads.
In CMS:
In Page (EN and NL):
Resolves #148
Closes #147 (outdated earlier attempt based on older routing)
1. Navigate to the [Files demo page (en)](https://feat-file-downloads.head-start.pages.dev/en/demos/file-demo/)
2. Review the links and verify that they work.
3. Switch to nl locale.
4. Review the links (see they now also display the language of the file) and verify that they …
=> feature: link to files (for download)

src/layouts/Default.astro, src/lib/datocms/index.ts, src/lib/seo/index.test.ts, src/lib/seo/index.ts, src/pages/[locale]/search/index.astro
- modified `siteName` and `titleSuffix` seo lib getters to be functions so they always use the locale from the moment they functions are invoked (instead of using the locale from the moment the file is first executed)
- add unit tests for seo lib function
- n/a
- run `npm run test:unit` -- this also happens automatically so you could also just check if the associated pipeline succeeds
=> test: SEO lib helpers

public/_headers
Adds cache header so all static assets generated by Astro are cached forever, making repeat visits faster.
Resolves #197
Verify the repeat view is faster on this deploy preview. 
Tests below are performed using [WebPageTest](https://www.webpagetest.org/) with "include repeat visit" checked.
[First visit](https://www.webpagetest.org/result/241108_AiDcN1_9KY/1/details/#waterfall_view_step1):
[Repeat visit](https://www.webpagetest.org/result/241108_AiDcN1_9KY/1/details/cached/):
[First visit (unchanged)](https://www.webpagetest.org/result/241108_BiDcSD_9Q8/1/details/#waterfall_view_step1)
[Repeat visit (faster)](https://www.webpagetest.org/result/241108_BiDcSD_9Q8/1/details/cached/)
- ~~I have added a …
=> perf: cache static assets (generated by Astro)

src/components/PerfHead/PerfHead.astro, src/components/PerfHead/README.md, src/layouts/Default.astro, src/lib/datocms/index.ts
Adds resource hints to preconnect DatoCMS assets and GraphQL (content delivery) API origins, so when the browser later does requests to those origins they are resolved faster.
I introduced a `<PerfHead>` component to bundle all performance related meta/link tags, similar to `<SeoHead>`.
Resolves #200
Verify the DatoCMS assets origin is `preconnect`ed earlier (1.3s before, 0.6 after) and images from that origin are loaded faster (1.8s before, 1.2s after) on this deploy preview. 
Tests below are performed using [WebPageTest](https://www.webpagetest.org/) with "include repeat visit" checked.
[test results](https://www.webpagetest.org/result/241107_AiDc9D_406/1/details/#waterfall_view_step1):
[test results](https://www.webpagetest.org/result/241109_BiDcJF_4RF/1/details/#waterfall_view_step1): …
=> perf: preconnect origins for faster pages

README.md, docs/blocks-and-components.md, docs/project-structure.md, docs/routing.md, docs/upgrading.md
Adds missing docs on:
- Page partials
- Client-side scripts
- Component testing
Resolves #71
Review updated documentation.
=> docs: page partials, client-side scripts, test files

src/lib/i18n/index.ts
- When `src/lib/i18n/index.ts` is run in the client, extract the current locale from the `lang` attribute. Otherwise, it just resets to the default locale. This fixes `t()` and `getLocale()` in combination with `client:load` components.
- Use either functions inside a component with `client:load`. Translations should now work as expected.
=> fix: conditionally set default locale on server & client

src/components/LocaleSelector/LocaleSelector.client.ts
#182 [introduced elements within the locale selector links](https://github.com/voorhoede/head-start/pull/182/files#diff-312432278fd76f34872189b8e676a79dd41e5abfe02c5f6fecb834c2abe399efR39), causing the client-side script to break as it could no longer get the `hreflang`. This in turn caused the `HEAD_START_LOCALE` cookie not to be set.
This change fixes this by ensuring it always finds the closest <a> tag first.
N/A (found this bug testing upgrade to Astro v5)
2. Switch locale using the locale selector
3. Verify the `HEAD_START_LOCALE` cookie contains the new value
4. Navigate to the root URL `/` again
5. Verify you're redirected to the locale you switched to before
- ~I have made updated relevant documentation files (in project README, docs/, etc)~
- ~I have added a …
=> fix(LocaleSelector): use closest <a> for hreflang

src/blocks/TextBlock/nodes/ItemLink.astro, src/components/Link/Link.astro, src/components/LinkToFile/LinkToFile.astro, src/components/LinkToRecord/LinkToRecord.astro
- Adds Astro builtin HTML tag definition to any component that spreads rest props.
1. Try adding any prop not explicitly defined in the `Astro.props` (for instance `class`) to a `<Link>` in another component. 
2. See that it does not produce an Typescript error when linting.
=> feat(Link): Allow `<a>` attrs as props in Typescript

src/blocks/ImageBlock/Image.astro, src/blocks/ImageBlock/Image.client.ts
Having Image.astro be the image-block web component is confusing
- Rename ImageBlock webcomponent to ImageComponent
1. Verify if images still work
=> style: rename Image web-component

src/blocks/VideoBlock/VideoBlock.client.ts
add feature check for navigator.connection since it is chromium only making video blocks fail outside of chromium browsers
Resolves #249 
Test Video Block in non Chromium browser
- ~I have made updated relevant documentation files (in project README, docs/, etc)~
=> Fix Video Blocks in non Chromium browsers

config/datocms/migrations/1735398092_emailAndPhoneLinks.ts, datocms-environment.ts, src/blocks/ActionBlock/ActionBlock.astro, src/blocks/ActionBlock/ActionBlock.fragment.graphql, src/blocks/ActionBlock/EmailLink.astro, src/blocks/ActionBlock/EmailLink.fragment.graphql, src/blocks/ActionBlock/PhoneLink.astro, src/blocks/ActionBlock/PhoneLink.fragment.graphql
> [!IMPORTANT] 
> Depends on #234, which should be merged first.
- Adds Email Link to easily send an email (with optional subject and body text).
- Adds Phone Link to easily start phone call, send sms (with optional text) or contact via WhatsApp (with optional message).
N/A
2. Navigate to Action Block demo > "Action block with Email Links" section
3. Verify all variations (mailto only, with subject, with subject + body) work
4. Navigate to Action Block demo > "Action block with Phone Links" section
5. Verify all variations (call, sms, whatsapp) work (best to check on both Android and iOS)
6. Go the the `email-and-phone-links` environment and play around with the new Email Link and Phone Link option in Action Blocks
7. Verify changes made are reflected in the web page …
=> feature: Email Link and Phone Link (in Action Block)

astro.config.ts, config/astro/service-worker-integration.ts, docs/assets.md, docs/decision-log/2025-01-11-service-worker.md, package-lock.json, package.json, scripts/service-worker-integration.ts, src/assets/service-worker.ts, src/layouts/PerfHead/PerfHead.astro
- Add service worker setup with basic network first strategy on HTML pages
- Made the decision to go for my own custom integration. It can serve as an example integration and I like the fact that we build our own service worker from a service-worker.ts file instead of generating one. I feel this is the most understandable for others and gives you maximum freedom over its implementation.
Resolves #199 
2. Open devtools --> Application
3. Verify a service worker is installed
4. Go offline, refresh the page and verify that the HTML page is still served
=> feature: Service worker (custom Astro integration)

README.md, docs/performance.md
> [!IMPORTANT] 
> ~Describes service worker in #242, which should be merged first.~ #242 is merged.
- Adds documentation on performance optimisations provided by Head Start.
- Adds documentation on performance tips for developers using Head Start.
- Fixes links to documentation (made relative so they work in more contexts).
Resolves #214
Read the new docs on Performance
=> docs: Performance

.gitignore, README.md, astro.config.ts, package-lock.json, package.json
Adds npm script to visualise both client & server bundles using [Sonda](https://sonda.dev/frameworks/astro), 
so that developers can analyse their code output and optimise it.
**Example client bundle:**
**Example server bundle:**
N/A
1. Check out this branch
2. Run `npm run analyze`
3. Verify the bundles are visualised in the browser
=> chore: "analyze" script

.gitignore, config/datocms/migrations/1734959319_customFilePaths.ts, datocms-environment.ts, package.json, scripts/download-file-proxy-map.ts, src/lib/routing/FileRoute.fragment.graphql, src/lib/routing/file.ts, src/lib/routing/index.ts, src/middleware/index.ts, src/middleware/proxy-files.ts
Makes files available under custom URLs by
- Adding an optional custom `slug` field to the File model.
- Adding middleware to proxy serve files under their custom slugs. For example `/my-files/example.pdf` serves `https://www.datocms-assets.com/145765/1730925112-dummy.pdf`.
Resolves #155
2. Navigate to the File Demo
3. Try the part under "File with a custom slug"
4. Verify that the file is proxied (available) under a custom slug
5. Play around with custom file slugs in the CMS
6. Verify your changes work (will need to run branch locally as deploy preview doesn't update)
=> feature: proxy files with custom slugs

package-lock.json, package.json, src/components/StructuredText/StructuredText.astro
- Upgrades `datocms-structured-text-utils` to newer version
- Safer extraction of node
- Typescript `satisfies` for return type validation.
2. Browse docs,
3. See that pages are still rendered
=> feat(StructuredText): safer extraction of node

astro.config.ts, config/output.ts, src/lib/datocms/index.ts, src/pages/404.astro, src/pages/[locale]/[...path]/index.astro, src/pages/[locale]/index.astro, src/pages/[locale]/search/opensearch.xml.ts
In order to cut down on type assertion via `as`, `datocmsRequest` should return a more workable type definition. Based on a passed type variable – or when omitted, the value of `output` in the astro config – `datocmsRequest` either has a return type that assumes the resource is available, or passes the expected return value based on the query.
- Export output mode from astro config.
- Allow asserted type override of datocmsRequest via `AssertReturnType`. 
1. Check out code locally
2. Open `@pages/[locale]/[...path]/index.astro`
3. Verify that the return value of `datocmsRequest` is typed by `PageQuery`, without any type assertion.
4. Replace comment `/* typeof prerender */` with a `true` or `false` value in the `datocmsRequest` type variables. 
5. Verify that any mention of `page` gets …
=> refactor: Type datocmsRequest based on output mode or prerender.

src/blocks/Blocks.astro
Report on possible issues that can occur when a new block is not added correctly.
- Check if there are fields other than `__typename` are passed for a specific block. If not, the block is probably missing in the query.
- Check if an Astro component is found for `__typename`. If not, the component is probably not added to the `blocksByTypename` map. 
- Better Typescript suppression
- More helpful hint
- Logging on server side when in development.
1. Check out & run the project locally
2. Go to the query.graphql for the home page.
3. Remove the TextBlockRecord spread
4. Visit the homepage.
5. Verify that you see `No block data found for "TextBlockRecord". Is the associated fragment included in the query?` in both your terminal and the browser console.
6. Remove the `TextBlockRecord` entry …
=> feat: more helpful errors when blocks are missing

src/lib/seo/index.ts
Add helper function to get proper locale data.
When there is only one locale configured in Dato, the `seoGlobal` is populated
with all data directly instead of with a locale key in between
=> fix(seo): also return seo settings when project has one locale

src/lib/datocms/tests/datocmsSearch.test.ts, src/lib/i18n/index.test.ts, src/lib/i18n/index.ts
Adds type-guard for locale and updates setLocale and tests with type-guard in place.
This allows tests relying on the locale to run with mock locales but provides type guard functions that assert strings to be a locale when passing.
Consider the following example in a function;
```ts
const locale = 'non-existent-locale';
if (!isLocale(locale)) return;
locales.includes(locale)
```
With `isLocale()`, the locale variable is now asserted to be a locale when the check passes, without linting errors when using a non existent locale.
Initially Typescript would assert locales.includes to contain an error during linting, resulting in head-start projects test/lint CI to fail when not all locales are present in the corresponding dato instance.
- Adds `isLocale()` type-guard
- Updates `setLocale()` …
=> refactor: allow string type in setLocale; mock locales in tests

src/components/LinkToRecord/LinkToRecord.test.ts, src/lib/routing/HomeRoute.fragment.graphql, src/lib/routing/index.test.ts
- Add `id` to HomeRouteFragment
1. Visit this page https://head-start.pages.dev/en/link-to-home-test
2. Verify that you get an error page (looks like a 404, but trust me, it's an error page)
3. Visit this page https://fix-home-route-id.head-start.pages.dev/en/link-to-home-test
4. Verify that you get a page with a link to Home.
=> fix(routing): add id to Home for StructuredText link

config/datocms/migrations/1748357537_pluginCustomTextStyles.ts, datocms-environment.ts, src/blocks/TextBlock/README.md, src/blocks/TextBlock/TextBlock.test.ts, src/blocks/TextBlock/nodes/Heading.astro, src/components/StructuredText/Nodes/Heading.astro, src/components/StructuredText/Nodes/Paragraph.astro, src/components/StructuredText/README.md
- Adds custom text styles with two example text style for paragraph and header
- Passes the style name as a class name to the Structured Text nodes
- Adds tests to verify if style is added
2. Navigate to Text Block demo
3. Verify that example for custom text styles is center aligned
=> Feat: add custom text styles plugin

docs/getting-started.md
- Small change I forgot in the last edit; refering to the prompts in our getting-started doc will make it easier for new users I think!
=> docs: refer to prompts in getting-started

.graphqlrc.ts, docs/cms-data-loading.md, docs/content-collections.md, scripts/download-translations.ts, src/blocks/PagePartialBlock/PagePartialBlock.astro, src/blocks/PagePartialBlock/PagePartialBlock.fragment.graphql, src/blocks/PagePartialBlock/PagePartialBlock.test.ts, src/components/StructuredData/StructuredData.astro, src/content/PagePartials/CollectionEntry.query.graphql, src/content/PagePartials/index.ts, src/content/config.ts, src/lib/content/index.test.ts, src/lib/content/index.ts, src/lib/datocms/index.ts, src/lib/datocms/tests/datocmsSearch.test.ts, src/lib/i18n/index.ts, src/lib/search/index.ts, src/lib/seo/index.ts, src/middleware/i18n.ts, src/pages/404.astro, src/pages/[locale]/search/index.astro, src/pages/[locale]/search/opensearch.xml.ts, src/pages/[locale]/search/results.partial.astro, src/pages/api/search/index.ts, src/pages/index.ts, tsconfig.json
- Adds initial implementation of content collections
- Uses content collections for page partials to reduce query complexity
- Handles localization within content collections
- Bypasses astro collections in development and preview
- Cleans up SiteLocale by using as const instead of enum for generated DatoCMS types
Partially resolves #166
2. Navigate to Page Partial Demo
4. Verify that Page Partials show up
=> feature: page partials content collection
